import { Eye, Trash2, Upload } from 'lucide-react'
import { IconButton } from '@/components/ui/IconButton'
import { useState } from 'react'
import type { PortalDocument } from './types'

const documentTypes = [{ id: 10, name: 'Original Quotation' }, { id: 20, name: 'Supporting document' }]

export function TypedAttachmentEditor({ documents, disabled, error, onUpload, onView, onRemove }: { documents: PortalDocument[]; disabled: boolean; error?: string; onUpload: (file: File, documentTypeId: number) => void; onView: (document: PortalDocument) => void; onRemove: (document: PortalDocument) => void }) {
  const [documentTypeId, setDocumentTypeId] = useState(10)
  return <section className="grid gap-3" data-invalid={error ? 'true' : undefined}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-heading font-semibold">Attachments</h2><p className="text-caption text-ink-muted">Original Quotation is required only when submitting.</p></div><div className="flex items-center gap-2"><select aria-label="Attachment type" value={documentTypeId} disabled={disabled} onChange={(event) => setDocumentTypeId(Number(event.target.value))} className="rounded-sm border border-border-subtle px-2 py-2 text-body">{documentTypes.map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</select><label className="inline-flex cursor-pointer items-center gap-2 rounded-sm border border-border-subtle px-3 py-2 text-body hover:bg-surface-muted"><Upload size={16} aria-hidden />Upload<input type="file" className="sr-only" disabled={disabled} onChange={(event) => { const file = event.target.files?.[0]; if (file) onUpload(file, documentTypeId); event.currentTarget.value = '' }} /></label></div></div>{documents.length === 0 ? <p className="border-y border-border-subtle py-3 text-body text-ink-muted">No attachments yet.</p> : <ul className="divide-y divide-border-subtle border-y border-border-subtle">{documents.map((document) => <li key={document.id} className="flex items-center gap-3 py-2"><div className="min-w-0 flex-1"><p className="truncate text-body font-medium">{document.fileName}</p><p className="mt-1 text-caption text-ink-muted">{document.documentTypeName}</p></div><IconButton label={`View ${document.fileName}`} onClick={() => onView(document)}><Eye size={16} /></IconButton><IconButton label={`Remove ${document.fileName}`} onClick={() => onRemove(document)} disabled={disabled}><Trash2 size={16} /></IconButton></li>)}</ul>}{error && <p className="text-caption text-danger">{error}</p>}</section>
}