import { ExternalLink, Paperclip, Trash2, Upload } from 'lucide-react'
import { IconButton } from '@/components/ui/IconButton'
import { appInputClassName } from '@/components/ui/inputStyles'
import { useState } from 'react'
import { formatFileSize } from './format'
import type { PortalDocument } from './types'

const documentTypes = [{ id: 10, name: 'Original Quotation' }, { id: 20, name: 'Supporting document' }]

export function TypedDocumentEditor({ documents, disabled, error, onUpload, onView, onRemove }: { documents: PortalDocument[]; disabled: boolean; error?: string; onUpload: (file: File, documentTypeId: number) => void; onView: (document: PortalDocument) => void; onRemove: (document: PortalDocument) => void }) {
  const [documentTypeId, setDocumentTypeId] = useState(10)
  return <section className="rounded-sm border border-border-subtle bg-white" data-invalid={error ? 'true' : undefined}><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border-subtle px-4 py-3"><div><h2 className="text-caption font-semibold uppercase tracking-[0.12em] text-ink-muted">Documents</h2><p className="mt-0.5 text-caption text-ink-muted">Original Quotation is required only when submitting.</p></div><div className="flex flex-wrap items-center gap-2"><select aria-label="Document type" value={documentTypeId} disabled={disabled} onChange={(event) => setDocumentTypeId(Number(event.target.value))} className={appInputClassName('sm', 'w-auto')}>{documentTypes.map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</select><label className="inline-flex h-8 cursor-pointer items-center gap-2 rounded-sm border border-border-subtle bg-white px-3 text-body font-medium hover:bg-surface-muted focus-within:outline-2 focus-within:outline-offset-2 focus-within:outline-accent"><Upload className="size-3.5" aria-hidden />Upload<input type="file" className="sr-only" disabled={disabled} onChange={(event) => { const file = event.target.files?.[0]; if (file) onUpload(file, documentTypeId); event.currentTarget.value = '' }} /></label></div></div>{documents.length === 0 ? <p className="px-4 py-6 text-center text-body text-ink-muted">No documents are attached to this request.</p> : <ul className="divide-y divide-border-subtle">{documents.map((document) => <li key={document.id} className="flex min-w-0 items-center gap-3 px-4 py-2.5"><Paperclip className="size-4 shrink-0 text-ink-soft" aria-hidden /><div className="min-w-0 flex-1"><p className="truncate text-body font-medium">{document.fileName}</p><p className="text-caption text-ink-muted">{[document.documentTypeName, formatFileSize(document.fileSize)].filter(Boolean).join(' · ')}</p></div><button type="button" onClick={() => onView(document)} className="inline-flex min-h-8 shrink-0 items-center gap-1 rounded-sm px-2 text-body text-accent hover:bg-accent-soft focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent">View<ExternalLink className="size-3.5" aria-hidden /></button><IconButton label={`Remove ${document.fileName}`} onClick={() => onRemove(document)} disabled={disabled}><Trash2 className="size-4" /></IconButton></li>)}</ul>}{error && <p className="border-t border-border-subtle px-4 py-2 text-caption text-danger">{error}</p>}</section>
}